//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cinema_App.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Account has been created succesfully!.
        /// </summary>
        public static string AccCreateSucces {
            get {
                return ResourceManager.GetString("AccCreateSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information.
        /// </summary>
        public static string Accinfo {
            get {
                return ResourceManager.GetString("Accinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Catering Item.
        /// </summary>
        public static string AddCateringItem {
            get {
                return ResourceManager.GetString("AddCateringItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Movie.
        /// </summary>
        public static string AddMovie {
            get {
                return ResourceManager.GetString("AddMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age has been changed succesfully!.
        /// </summary>
        public static string AgeChangeSucces {
            get {
                return ResourceManager.GetString("AgeChangeSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Please enter a valid number!.
        /// </summary>
        public static string AgeNotValid {
            get {
                return ResourceManager.GetString("AgeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the amount you want to enter, press enter if you want to return to the catering menu:.
        /// </summary>
        public static string AmountMess {
            get {
                return ResourceManager.GetString("AmountMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catering.
        /// </summary>
        public static string Catering {
            get {
                return ResourceManager.GetString("Catering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catering menu.
        /// </summary>
        public static string CateringMenu {
            get {
                return ResourceManager.GetString("CateringMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently selected menu-item: .
        /// </summary>
        public static string CaterName {
            get {
                return ResourceManager.GetString("CaterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change account information.
        /// </summary>
        public static string ChangeAcc {
            get {
                return ResourceManager.GetString("ChangeAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change age.
        /// </summary>
        public static string ChangeAge {
            get {
                return ResourceManager.GetString("ChangeAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email-address.
        /// </summary>
        public static string ChangeMail {
            get {
                return ResourceManager.GetString("ChangeMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change name.
        /// </summary>
        public static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change user information.
        /// </summary>
        public static string ChangeUserInfo {
            get {
                return ResourceManager.GetString("ChangeUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change username.
        /// </summary>
        public static string ChangeUserName {
            get {
                return ResourceManager.GetString("ChangeUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-address has been changed succesfully!.
        /// </summary>
        public static string EmailChangeSucces {
            get {
                return ResourceManager.GetString("EmailChangeSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter a valid email-address!.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input can not be empty!.
        /// </summary>
        public static string EmptyInput {
            get {
                return ResourceManager.GetString("EmptyInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **empty**.
        /// </summary>
        public static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter your age:.
        /// </summary>
        public static string EnterAge {
            get {
                return ResourceManager.GetString("EnterAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the auditorium name: .
        /// </summary>
        public static string EnterAudi {
            get {
                return ResourceManager.GetString("EnterAudi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter absolute path for image file:.
        /// </summary>
        public static string EnterAudiPath {
            get {
                return ResourceManager.GetString("EnterAudiPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your creditcard number: .
        /// </summary>
        public static string EnterCreditcard {
            get {
                return ResourceManager.GetString("EnterCreditcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter item name:.
        /// </summary>
        public static string EnterItemName {
            get {
                return ResourceManager.GetString("EnterItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter your email-address:.
        /// </summary>
        public static string EnterMail {
            get {
                return ResourceManager.GetString("EnterMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the movie&apos;s age rating:.
        /// </summary>
        public static string EnterMovieAgeRating {
            get {
                return ResourceManager.GetString("EnterMovieAgeRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the movie&apos;s description:.
        /// </summary>
        public static string EnterMovieDesc {
            get {
                return ResourceManager.GetString("EnterMovieDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the movie&apos;s review score:.
        /// </summary>
        public static string EnterMovieReviewScore {
            get {
                return ResourceManager.GetString("EnterMovieReviewScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter movie&apos;s title:.
        /// </summary>
        public static string EnterMovieTitle {
            get {
                return ResourceManager.GetString("EnterMovieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the movie&apos;s trailer url:.
        /// </summary>
        public static string EnterMovieTrailerUrl {
            get {
                return ResourceManager.GetString("EnterMovieTrailerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter your name:.
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new password.
        /// </summary>
        public static string EnterNewPW {
            get {
                return ResourceManager.GetString("EnterNewPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter price:.
        /// </summary>
        public static string EnterPrice {
            get {
                return ResourceManager.GetString("EnterPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter your password:.
        /// </summary>
        public static string EnterPW {
            get {
                return ResourceManager.GetString("EnterPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the desired seat(s), type &apos;cancel&apos; to go back to the movies or press done if you want to add the seats to your basket:.
        /// </summary>
        public static string EnterSeats {
            get {
                return ResourceManager.GetString("EnterSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ex: For seat X:10 Y:12 enter &apos;10,12&apos; without the qoutes. For multiple seats enter the cooridinates seperated by a space. Ex: &apos;10,12 10,13&apos;..
        /// </summary>
        public static string EnterSeatsExample {
            get {
                return ResourceManager.GetString("EnterSeatsExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Enter your username:.
        /// </summary>
        public static string EnterUserName {
            get {
                return ResourceManager.GetString("EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by: INF1C group 3.
        /// </summary>
        public static string GroupInfo {
            get {
                return ResourceManager.GetString("GroupInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Auditorium.
        /// </summary>
        public static string ImportAuditorium {
            get {
                return ResourceManager.GetString("ImportAuditorium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Double.
        /// </summary>
        public static string InvalidDoubleInput {
            get {
                return ResourceManager.GetString("InvalidDoubleInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User.
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to return to the main menu.
        /// </summary>
        public static string KeyPressToReturn {
            get {
                return ResourceManager.GetString("KeyPressToReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingMessage {
            get {
                return ResourceManager.GetString("LoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with existing account.
        /// </summary>
        public static string LoginMenu {
            get {
                return ResourceManager.GetString("LoginMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   You will be asked to login in a few moments....
        /// </summary>
        public static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login screen.
        /// </summary>
        public static string LogScreen {
            get {
                return ResourceManager.GetString("LogScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string MainMenuName {
            get {
                return ResourceManager.GetString("MainMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Catering Items.
        /// </summary>
        public static string ManageCateringItems {
            get {
                return ResourceManager.GetString("ManageCateringItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Movies.
        /// </summary>
        public static string MangeMovies {
            get {
                return ResourceManager.GetString("MangeMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Catalogue.
        /// </summary>
        public static string MovCat {
            get {
                return ResourceManager.GetString("MovCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Score.
        /// </summary>
        public static string MoveReviewScore {
            get {
                return ResourceManager.GetString("MoveReviewScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age Rating.
        /// </summary>
        public static string MovieAge {
            get {
                return ResourceManager.GetString("MovieAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string MovieDesc {
            get {
                return ResourceManager.GetString("MovieDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string MoviePrice {
            get {
                return ResourceManager.GetString("MoviePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Auditorium.
        /// </summary>
        public static string MovieSetAuditorium {
            get {
                return ResourceManager.GetString("MovieSetAuditorium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string MovieTitle {
            get {
                return ResourceManager.GetString("MovieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer.
        /// </summary>
        public static string MovieTrailer {
            get {
                return ResourceManager.GetString("MovieTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinema App\n.
        /// </summary>
        public static string NameApp {
            get {
                return ResourceManager.GetString("NameApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name has been changed succesfully!.
        /// </summary>
        public static string NameChangeSucces {
            get {
                return ResourceManager.GetString("NameChangeSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Name cannot be empty!.
        /// </summary>
        public static string NameNotEmpty {
            get {
                return ResourceManager.GetString("NameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrderHisotry {
            get {
                return ResourceManager.GetString("OrderHisotry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order History.
        /// </summary>
        public static string OrderHistory {
            get {
                return ResourceManager.GetString("OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order-id: .
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order created succesfully.
        /// </summary>
        public static string Ordersucces {
            get {
                return ResourceManager.GetString("Ordersucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///  Use the ↑ and ↓ keys to selection and item..
        /// </summary>
        public static string PressArrow {
            get {
                return ResourceManager.GetString("PressArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to return to the movie catalogue....
        /// </summary>
        public static string PressKeyToMovCat {
            get {
                return ResourceManager.GetString("PressKeyToMovCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Press return to make your choice.
        /// </summary>
        public static string PressReturn {
            get {
                return ResourceManager.GetString("PressReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed succesfully.
        /// </summary>
        public static string PWChangeSucces {
            get {
                return ResourceManager.GetString("PWChangeSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Password cannot be empty.
        /// </summary>
        public static string PWNotEmpty {
            get {
                return ResourceManager.GetString("PWNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register New Account.
        /// </summary>
        public static string RegisterNew {
            get {
                return ResourceManager.GetString("RegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Screen.
        /// </summary>
        public static string RegScreen {
            get {
                return ResourceManager.GetString("RegScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Item.
        /// </summary>
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservate seat.
        /// </summary>
        public static string ReservateSeat {
            get {
                return ResourceManager.GetString("ReservateSeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to return to the main menu....
        /// </summary>
        public static string ReturnToMain {
            get {
                return ResourceManager.GetString("ReturnToMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Main Menu.
        /// </summary>
        public static string ReturnToMainOption {
            get {
                return ResourceManager.GetString("ReturnToMainOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat Reservation.
        /// </summary>
        public static string SeatReservation {
            get {
                return ResourceManager.GetString("SeatReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username has been changed succesfully!.
        /// </summary>
        public static string UserNameChangeSucces {
            get {
                return ResourceManager.GetString("UserNameChangeSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Username is already in use!.
        /// </summary>
        public static string UsernameInUse {
            get {
                return ResourceManager.GetString("UsernameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Username cannot be empty!.
        /// </summary>
        public static string UsernameNotEmpty {
            get {
                return ResourceManager.GetString("UsernameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   This user does not exist..
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string VarAge {
            get {
                return ResourceManager.GetString("VarAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-address.
        /// </summary>
        public static string VarEmailAddress {
            get {
                return ResourceManager.GetString("VarEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string VarName {
            get {
                return ResourceManager.GetString("VarName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string VarUserName {
            get {
                return ResourceManager.GetString("VarUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View account information.
        /// </summary>
        public static string ViewAcc {
            get {
                return ResourceManager.GetString("ViewAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Current Movies.
        /// </summary>
        public static string ViewCurrentMovies {
            get {
                return ResourceManager.GetString("ViewCurrentMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to view this..
        /// </summary>
        public static string ViewPermError {
            get {
                return ResourceManager.GetString("ViewPermError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Please wait while we are creating your account, this might take a few seconds....
        /// </summary>
        public static string WaitAccCreateMess {
            get {
                return ResourceManager.GetString("WaitAccCreateMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   You will be redirected to the main menu in a few moments....
        /// </summary>
        public static string WaitingMess {
            get {
                return ResourceManager.GetString("WaitingMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Wrong password, please try again..
        /// </summary>
        public static string WrongPW {
            get {
                return ResourceManager.GetString("WrongPW", resourceCulture);
            }
        }
    }
}
